// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using OpenLedg.Infrastructure.Persistence;

#nullable disable

namespace OpenLedg.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(OlgpDbContext))]
    [Migration("20260913214332_InitialOlgp")]
    partial class InitialOlgp
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("olgp")
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("OpenLedg.Domain.Participants.BaseParticipant", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AmlStatus")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("aml_status");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("idempotency_key");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("kind");

                    b.Property<string>("KycStatus")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("kyc_status");

                    b.HasKey("Id");

                    b.HasIndex("IdempotencyKey")
                        .IsUnique();

                    b.ToTable("participants", "olgp", t =>
                        {
                            t.HasCheckConstraint("ck_participants_aml", "aml_status IN ('Pending', 'Approved', 'Rejected', 'Suspended')");

                            t.HasCheckConstraint("ck_participants_kind", "kind IN ('Individual', 'Corporate', 'PaymentInitiator')");

                            t.HasCheckConstraint("ck_participants_kyc", "kyc_status IN ('Pending', 'Approved', 'Rejected', 'Suspended')");

                            t.HasCheckConstraint("ck_participants_shape", "(kind = 'Individual' AND cpf IS NOT NULL AND cpf ~ '^[0-9]{11}$' AND full_name IS NOT NULL\n    AND cnpj IS NULL AND legal_name IS NULL AND organization_id IS NULL AND display_name IS NULL)\nOR (kind = 'Corporate' AND cnpj IS NOT NULL AND cnpj ~ '^[A-Z0-9]{12}[0-9]{2}$' AND legal_name IS NOT NULL\n    AND cpf IS NULL AND full_name IS NULL AND organization_id IS NULL AND display_name IS NULL)\nOR (kind = 'PaymentInitiator' AND organization_id IS NOT NULL AND display_name IS NOT NULL\n    AND cpf IS NULL AND full_name IS NULL AND cnpj IS NULL AND legal_name IS NULL)");

                            t.HasCheckConstraint("ck_participants_uuid_v4", "substring(id::text, 15, 1) = '4'");
                        });

                    b.HasDiscriminator<string>("Kind");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("OpenLedg.Domain.Participants.LegalRepresentative", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("character varying(11)")
                        .HasColumnName("cpf");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("full_name");

                    b.Property<Guid>("ParticipantId")
                        .HasColumnType("uuid")
                        .HasColumnName("participant_id");

                    b.Property<string>("ParticipantKind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("participant_kind");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("role");

                    b.HasKey("Id");

                    b.HasIndex("ParticipantId", "Cpf")
                        .IsUnique();

                    b.HasIndex("ParticipantId", "ParticipantKind");

                    b.ToTable("legal_representatives", "olgp", t =>
                        {
                            t.HasCheckConstraint("ck_legal_representatives_participant_kind", "participant_kind IN ('Corporate')");
                        });
                });

            modelBuilder.Entity("OpenLedg.Domain.Participants.PixKey", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("DictReference")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("dict_reference");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("kind");

                    b.Property<Guid>("ParticipantId")
                        .HasColumnType("uuid")
                        .HasColumnName("participant_id");

                    b.Property<string>("ParticipantKind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("participant_kind");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("value");

                    b.HasKey("Id");

                    b.HasIndex("DictReference")
                        .IsUnique();

                    b.HasIndex("Kind", "Value")
                        .IsUnique();

                    b.HasIndex("ParticipantId", "ParticipantKind");

                    b.ToTable("pix_keys", "olgp", t =>
                        {
                            t.HasCheckConstraint("ck_pix_keys_participant_kind", "participant_kind IN ('Individual')");
                        });
                });

            modelBuilder.Entity("OpenLedg.Domain.Routing.SettlementRoute", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("LedgerAccountId")
                        .IsRequired()
                        .HasMaxLength(39)
                        .HasColumnType("character varying(39)")
                        .HasColumnName("ledger_account_id");

                    b.Property<Guid>("ParticipantId")
                        .HasColumnType("uuid")
                        .HasColumnName("participant_id");

                    b.Property<string>("ParticipantKind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("participant_kind");

                    b.HasKey("Id");

                    b.HasIndex("LedgerAccountId")
                        .IsUnique();

                    b.HasIndex("ParticipantId", "ParticipantKind");

                    b.ToTable("settlement_routes", "routing", t =>
                        {
                            t.HasCheckConstraint("ck_routes_account_id", "ledger_account_id ~ '^[1-9][0-9]{0,38}$' AND ledger_account_id::numeric < 340282366920938463463374607431768211455");

                            t.HasCheckConstraint("ck_settlement_routes_participant_kind", "participant_kind IN ('Individual', 'Corporate')");
                        });
                });

            modelBuilder.Entity("OpenLedg.Domain.Security.AuthenticationProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Issuer")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("issuer");

                    b.Property<string>("MfaSecretReference")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("mfa_secret_reference");

                    b.Property<Guid>("ParticipantId")
                        .HasColumnType("uuid")
                        .HasColumnName("participant_id");

                    b.Property<string>("ParticipantKind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("participant_kind");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("subject");

                    b.Property<string>("WebAuthnCredentialId")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("web_authn_credential_id");

                    b.HasKey("Id");

                    b.HasIndex("ParticipantId")
                        .IsUnique();

                    b.HasIndex("Issuer", "Subject")
                        .IsUnique();

                    b.HasIndex("ParticipantId", "ParticipantKind");

                    b.ToTable("authentication_profiles", "security", t =>
                        {
                            t.HasCheckConstraint("ck_authentication_profiles_participant_kind", "participant_kind IN ('Individual')");
                        });
                });

            modelBuilder.Entity("OpenLedg.Domain.Security.InitiatorIntegration", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CertificateExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("certificate_expires_at");

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("client_id");

                    b.Property<string>("DpopAlgorithm")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("dpop_algorithm");

                    b.Property<string>("DpopPublicJwksUri")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("dpop_public_jwks_uri");

                    b.Property<string>("MtlsCertificatePem")
                        .IsRequired()
                        .HasMaxLength(16384)
                        .HasColumnType("character varying(16384)")
                        .HasColumnName("mtls_certificate_pem");

                    b.Property<Guid>("ParticipantId")
                        .HasColumnType("uuid")
                        .HasColumnName("participant_id");

                    b.Property<string>("ParticipantKind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("participant_kind");

                    b.Property<string>("PrivateKeyReference")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("private_key_reference");

                    b.Property<string>("TokenEndpoint")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("token_endpoint");

                    b.HasKey("Id");

                    b.HasIndex("ParticipantId")
                        .IsUnique();

                    b.HasIndex("ParticipantId", "ParticipantKind");

                    b.ToTable("initiator_integrations", "security", t =>
                        {
                            t.HasCheckConstraint("ck_initiator_integrations_participant_kind", "participant_kind IN ('PaymentInitiator')");
                        });
                });

            modelBuilder.Entity("OpenLedg.Domain.Security.ParticipantPermission", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ParticipantId")
                        .HasColumnType("uuid")
                        .HasColumnName("participant_id");

                    b.Property<string>("ParticipantKind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("participant_kind");

                    b.Property<string>("Permission")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("permission");

                    b.HasKey("Id");

                    b.HasIndex("ParticipantId", "ParticipantKind");

                    b.HasIndex("ParticipantId", "Permission")
                        .IsUnique();

                    b.ToTable("participant_permissions", "security");
                });

            modelBuilder.Entity("OpenLedg.Domain.Security.WebhookConfiguration", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ParticipantId")
                        .HasColumnType("uuid")
                        .HasColumnName("participant_id");

                    b.Property<string>("ParticipantKind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("participant_kind");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("url");

                    b.Property<string>("VerificationPublicKeyPem")
                        .IsRequired()
                        .HasMaxLength(4096)
                        .HasColumnType("character varying(4096)")
                        .HasColumnName("verification_public_key_pem");

                    b.HasKey("Id");

                    b.HasIndex("ParticipantId", "ParticipantKind");

                    b.HasIndex("ParticipantId", "Url")
                        .IsUnique();

                    b.ToTable("webhook_configurations", "security", t =>
                        {
                            t.HasCheckConstraint("ck_webhook_configurations_participant_kind", "participant_kind IN ('Corporate')");
                        });
                });

            modelBuilder.Entity("OpenLedg.Domain.Participants.CorporateClient", b =>
                {
                    b.HasBaseType("OpenLedg.Domain.Participants.BaseParticipant");

                    b.Property<string>("Cnpj")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("character varying(14)")
                        .HasColumnName("cnpj");

                    b.Property<string>("LegalName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("legal_name");

                    b.HasIndex("Cnpj")
                        .IsUnique()
                        .HasFilter("cnpj IS NOT NULL");

                    b.ToTable(t =>
                        {
                            t.HasCheckConstraint("ck_participants_aml", "aml_status IN ('Pending', 'Approved', 'Rejected', 'Suspended')");

                            t.HasCheckConstraint("ck_participants_kind", "kind IN ('Individual', 'Corporate', 'PaymentInitiator')");

                            t.HasCheckConstraint("ck_participants_kyc", "kyc_status IN ('Pending', 'Approved', 'Rejected', 'Suspended')");

                            t.HasCheckConstraint("ck_participants_shape", "(kind = 'Individual' AND cpf IS NOT NULL AND cpf ~ '^[0-9]{11}$' AND full_name IS NOT NULL\n    AND cnpj IS NULL AND legal_name IS NULL AND organization_id IS NULL AND display_name IS NULL)\nOR (kind = 'Corporate' AND cnpj IS NOT NULL AND cnpj ~ '^[A-Z0-9]{12}[0-9]{2}$' AND legal_name IS NOT NULL\n    AND cpf IS NULL AND full_name IS NULL AND organization_id IS NULL AND display_name IS NULL)\nOR (kind = 'PaymentInitiator' AND organization_id IS NOT NULL AND display_name IS NOT NULL\n    AND cpf IS NULL AND full_name IS NULL AND cnpj IS NULL AND legal_name IS NULL)");

                            t.HasCheckConstraint("ck_participants_uuid_v4", "substring(id::text, 15, 1) = '4'");
                        });

                    b.HasDiscriminator().HasValue("Corporate");
                });

            modelBuilder.Entity("OpenLedg.Domain.Participants.IndividualClient", b =>
                {
                    b.HasBaseType("OpenLedg.Domain.Participants.BaseParticipant");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("character varying(11)")
                        .HasColumnName("cpf");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("full_name");

                    b.HasIndex("Cpf")
                        .IsUnique()
                        .HasFilter("cpf IS NOT NULL");

                    b.ToTable(t =>
                        {
                            t.HasCheckConstraint("ck_participants_aml", "aml_status IN ('Pending', 'Approved', 'Rejected', 'Suspended')");

                            t.HasCheckConstraint("ck_participants_kind", "kind IN ('Individual', 'Corporate', 'PaymentInitiator')");

                            t.HasCheckConstraint("ck_participants_kyc", "kyc_status IN ('Pending', 'Approved', 'Rejected', 'Suspended')");

                            t.HasCheckConstraint("ck_participants_shape", "(kind = 'Individual' AND cpf IS NOT NULL AND cpf ~ '^[0-9]{11}$' AND full_name IS NOT NULL\n    AND cnpj IS NULL AND legal_name IS NULL AND organization_id IS NULL AND display_name IS NULL)\nOR (kind = 'Corporate' AND cnpj IS NOT NULL AND cnpj ~ '^[A-Z0-9]{12}[0-9]{2}$' AND legal_name IS NOT NULL\n    AND cpf IS NULL AND full_name IS NULL AND organization_id IS NULL AND display_name IS NULL)\nOR (kind = 'PaymentInitiator' AND organization_id IS NOT NULL AND display_name IS NOT NULL\n    AND cpf IS NULL AND full_name IS NULL AND cnpj IS NULL AND legal_name IS NULL)");

                            t.HasCheckConstraint("ck_participants_uuid_v4", "substring(id::text, 15, 1) = '4'");
                        });

                    b.HasDiscriminator().HasValue("Individual");
                });

            modelBuilder.Entity("OpenLedg.Domain.Participants.PaymentInitiator", b =>
                {
                    b.HasBaseType("OpenLedg.Domain.Participants.BaseParticipant");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("display_name");

                    b.Property<string>("OrganizationId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("organization_id");

                    b.HasIndex("OrganizationId")
                        .IsUnique()
                        .HasFilter("organization_id IS NOT NULL");

                    b.ToTable(t =>
                        {
                            t.HasCheckConstraint("ck_participants_aml", "aml_status IN ('Pending', 'Approved', 'Rejected', 'Suspended')");

                            t.HasCheckConstraint("ck_participants_kind", "kind IN ('Individual', 'Corporate', 'PaymentInitiator')");

                            t.HasCheckConstraint("ck_participants_kyc", "kyc_status IN ('Pending', 'Approved', 'Rejected', 'Suspended')");

                            t.HasCheckConstraint("ck_participants_shape", "(kind = 'Individual' AND cpf IS NOT NULL AND cpf ~ '^[0-9]{11}$' AND full_name IS NOT NULL\n    AND cnpj IS NULL AND legal_name IS NULL AND organization_id IS NULL AND display_name IS NULL)\nOR (kind = 'Corporate' AND cnpj IS NOT NULL AND cnpj ~ '^[A-Z0-9]{12}[0-9]{2}$' AND legal_name IS NOT NULL\n    AND cpf IS NULL AND full_name IS NULL AND organization_id IS NULL AND display_name IS NULL)\nOR (kind = 'PaymentInitiator' AND organization_id IS NOT NULL AND display_name IS NOT NULL\n    AND cpf IS NULL AND full_name IS NULL AND cnpj IS NULL AND legal_name IS NULL)");

                            t.HasCheckConstraint("ck_participants_uuid_v4", "substring(id::text, 15, 1) = '4'");
                        });

                    b.HasDiscriminator().HasValue("PaymentInitiator");
                });

            modelBuilder.Entity("OpenLedg.Domain.Participants.LegalRepresentative", b =>
                {
                    b.HasOne("OpenLedg.Domain.Participants.BaseParticipant", null)
                        .WithMany()
                        .HasForeignKey("ParticipantId", "ParticipantKind")
                        .HasPrincipalKey("Id", "Kind")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("OpenLedg.Domain.Participants.PixKey", b =>
                {
                    b.HasOne("OpenLedg.Domain.Participants.BaseParticipant", null)
                        .WithMany()
                        .HasForeignKey("ParticipantId", "ParticipantKind")
                        .HasPrincipalKey("Id", "Kind")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("OpenLedg.Domain.Routing.SettlementRoute", b =>
                {
                    b.HasOne("OpenLedg.Domain.Participants.BaseParticipant", null)
                        .WithMany()
                        .HasForeignKey("ParticipantId", "ParticipantKind")
                        .HasPrincipalKey("Id", "Kind")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("OpenLedg.Domain.Security.AuthenticationProfile", b =>
                {
                    b.HasOne("OpenLedg.Domain.Participants.BaseParticipant", null)
                        .WithMany()
                        .HasForeignKey("ParticipantId", "ParticipantKind")
                        .HasPrincipalKey("Id", "Kind")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("OpenLedg.Domain.Security.InitiatorIntegration", b =>
                {
                    b.HasOne("OpenLedg.Domain.Participants.BaseParticipant", null)
                        .WithMany()
                        .HasForeignKey("ParticipantId", "ParticipantKind")
                        .HasPrincipalKey("Id", "Kind")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("OpenLedg.Domain.Security.ParticipantPermission", b =>
                {
                    b.HasOne("OpenLedg.Domain.Participants.BaseParticipant", null)
                        .WithMany()
                        .HasForeignKey("ParticipantId", "ParticipantKind")
                        .HasPrincipalKey("Id", "Kind")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("OpenLedg.Domain.Security.WebhookConfiguration", b =>
                {
                    b.HasOne("OpenLedg.Domain.Participants.BaseParticipant", null)
                        .WithMany()
                        .HasForeignKey("ParticipantId", "ParticipantKind")
                        .HasPrincipalKey("Id", "Kind")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
